site_name: DDI documentation
docs_dir: '.'
site_dir: '../site'  # This will be a temporary build folder
nav:
    - Index: index.md
    - CRF: 
      - 'TSD File Import': dditools/tsdimport.md
      - 'Scan Split & Upload': dditools/crfsplit.md
      - 'OMR-CRF Data Import': dditools/crfimport.md
theme: readthedocs
